disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - control_statement
#  - file_length
#  - force_cast
#  - function_body_length
#  - leading_whitespace
  - line_length
#  - nesting
#  - operator_whitespace
#  - return_arrow_whitespace
#  - todo
#  - trailing_newline
  - trailing_whitespace
  - type_body_length
#  - type_name
#  - variable_name
#included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
#  - Source
#excluded: # paths to ignore during linting. overridden by `included`.
#  - Carthage
#  - Pods
# parameterized rules can be customized from this configuration file
# line_length: 200
# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 300 # warning
  - 400 # error
# parameterized rules are first parameterized as a warning level, then error level.
variable_name_max_length:
  - 40 # warning
  - 60 # error
# parameterized rules are first parameterized as a warning level, then error level.
variable_name_min_length:
  - 1 # warning
  - 1 # error

